### ISSUE TITLE
How to make recvonly connection on SFURoom?

### ISSUE THREAD

**Issue by shukob** [nttcom/SkyWay-JS-Sample#4]
Hi, I want to do broadcasting with SFURoom, for now it seems to require both audio/video stream so that one can receive them from peer. (Then I disable tracks for them to be not delivered to peers.)
Can I specify some peer as recvonly using SFURoom?
Thanks in advance.

**Comment by yusuke84** [comment]
Broadcasting can be realized with SFU by using 'receive only mode'.

```
- peer.joinRoom(roomName, [options]);
  - options {object}
    - stream {MediaStream}
      - The MediaStream object to send to the other users in the room. Works in receive only mode if not defined.
```

Ref: http://nttcom.github.io/skyway/en/room-docs.html

However, there is a possibility that there is a bug.
Ref: https://support.skyway.io/hc/ja/community/posts/115000612268/comments/115001040828

**Comment by shukob** [comment]
Thank you for support!

I already tested stream: null,  and not received any stream from broadcaster. But it seems to be a bug of the SFU and it was actually a delay as mentioned in the thread.
